# Generated by Django 5.1.5 on 2025-03-22 23:31

import config.utils.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="products/",
                validators=[
                    config.utils.image_validators.validate_image_dimensions,
                    config.utils.image_validators.validate_image_size,
                ],
            ),
        ),
    ]
