# Generated by Django 5.1.5 on 2025-04-09 19:34

import config.utils.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[config.utils.image_validators.validate_image_size, config.utils.image_validators.validate_image_dimensions]),
        ),
    ]
